
theme: jekyll-theme-minimal
title: The Yocto Jester
description: Online home of that <a href="https://mender.io/">Mender</a>, <a href="https://www.yoctoproject.org/">Yocto Project</a> and <a href="https://www.openembedded.org/wiki/Main_Page/">OpenEmbedded</a> guy